---
title: Gasoline Prices in Mexico
subtitle: "*Fuel Price Fluctuations, A Constant Concern*"
date: '2025-02-03'
date-format: MMM, YYYY
author: Jesus L. Monroy
abstract: |
  Gasoline prices in Mexico are a complex issue influenced by various factors.
  In this article we examine the gasoline prices in the 32 States that constitute Mexico and also their differences in cost, sale price and profits.
  Challenges remain in stabilizing prices and mitigating the impact on consumers and the economy.
format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 950px
      margin-width: 150px
    reference-location: margin
    fig-cap-location: margin
    other-links:
      - text: Medium
        icon: medium
        href: https://medium.com/@jesuslm
      - text: Linkedin
        icon: linkedin
        href: https://www.linkedin.com/in/j3sus-lm
      - text: Twitter
        icon: twitter
        href: https://x.com/j3suslm
    code-fold: show
    code-summary: Show code
    code-tools:
      source: false
      toggle: true
      caption: code
    toc: true
    toc-depth: 3
    html-math-method: katex
    colorlinks: true
    execute:
      echo: true
code-line-numbers: false
code-copy: false
code-overflow: wrap
jupyter: python3
---

```{python}
import polars as pl
import duckdb as db
import plotly.express as px
from plotnine import *
```

### Connect to database

```{python}
conn = db.connect('data/my_database.db')
```

### Create dataframe

```{python}
df = conn.sql('select * from gas_stations').pl()
```

### Close database connection

```{python}
conn.close()
```

### Table overview

```{python}
df = (
    df.select('entidad'
              , 'municipio'
              , 'precio_tar'
              , 'precio_vendedores'
              , 'ganancia')
        .rename({
            'entidad':'state',
            'municipio':'municipality',
            'precio_tar':'gasoline_cost',
            'precio_vendedores':'sale_price',
            'ganancia':'profit',
        })
).with_columns(
    (pl.col('profit')/pl.col('gasoline_cost')).alias('profit%'),
    mun_state=pl.col('municipality')+', '+pl.col('state')
)
```

```{python}
df.select(pl.exclude('mun_state')).head()
```

```{python}
#| tbl-cap: Dataset preview

( 
    df.select(pl.exclude('mun_state'))
        .to_pandas()
        .head()
        .style
        .hide()    
        .format({'gasoline_cost': '${:,.2f}',
                 'sale_price': '${:.2f}',
                 'profit': '${:.2f}',
                 'profit%': '{:.2%}',})
)
```

### Group data by State

```{python}
states = (
        df.group_by('state')
            .agg(pl.col('gasoline_cost','sale_price','profit', 'profit%').mean())
            .sort('state')
        )
```

### Group data by municipality

```{python}
municipalities = (
        df.group_by('mun_state')
            .agg(pl.col('gasoline_cost','sale_price','profit','profit%').mean())
            .sort('mun_state')
        )
```

## Top 05 States with highest gasoline prices

```{python}
#| tbl-cap: Top 05 States with highest prices

(
    states
        .top_k(5, by='sale_price')
        .to_pandas()
        .style
        .hide()    
        .format({'gasoline_cost': '${:,.2f}',
                 'sale_price': '${:.2f}',
                 'profit': '${:.2f}',
                 'profit%': '{:.2%}',})
)
```

## Top 05 States with lowest gasoline prices

```{python}
#| tbl-cap: Top 05 States with lowest prices

(
    states
        .bottom_k(5, by='sale_price')
        .to_pandas()
        .style
        .hide()    
        .format({'gasoline_cost': '${:,.2f}',
                 'sale_price': '${:.2f}',
                 'profit': '${:.2f}',
                 'profit%': '{:.2%}',})
)
```

## Top 05 Municipalities with highest gasoline prices

```{python}
#| tbl-cap: Top 05 Municipalities with highest prices

(
    municipalities
        .top_k(5, by='sale_price')
        .to_pandas()
        .style
        .hide()    
        .format({'gasoline_cost': '${:,.2f}',
                 'sale_price': '${:.2f}',
                 'profit': '${:.2f}',
                 'profit%': '{:.2%}',})
)
```

## Top 05 Municipalities with lowest gasoline prices

```{python}
#| tbl-cap: Top 05 Municipalities with lowest prices

(
    municipalities
        .bottom_k(5, by='sale_price')
        .to_pandas()
        .style
        .hide()    
        .format({'gasoline_cost': '${:,.2f}',
                 'sale_price': '${:.2f}',
                 'profit': '${:.2f}',
                 'profit%': '{:.2%}',})
)
```

# Average Gasoline Price by State

```{python}
#| label: fig-states
#| fig-cap: Average Gasoline Prices by State

(
    ggplot(states, mapping=aes(x='state', y='sale_price'))
        + geom_bar(stat='identity', fill="#4c72b0")
        + coord_flip()
        + scale_y_continuous(limits=(0, 25))
        + labs(x='State',
               y='Gasoline price')
        + theme(axis_text_y=element_text(rotation=0),
               figure_size=(8.5, 6))
)
```

# Profit by State

```{python}
#| label: fig-states-profit
#| fig-cap: Profit by State

(
    ggplot(states, mapping=aes(x='state', y='profit'))
        + geom_bar(stat='identity', fill="#800020")
        + coord_flip()
        + scale_y_continuous(limits=(0, 3.4))
        + labs(x='State',
               y='Profit')
        + theme(axis_text_y=element_text(rotation=0),
               figure_size=(8.5, 6))
)
```

# Dispersion of Gasoline Prices

```{python}
#| label: fig-municipalities
#| fig-cap: Dispersion of Gasoline Prices by State

(
    ggplot(data=df, mapping=aes(x='state', y='sale_price', fill='state')) 
    + geom_boxplot()
    + coord_flip()
    + scale_y_continuous(limits=(20, 25.9))
    + labs(x='State',
           y='Gasoline price')
    + theme(legend_position='none',
           figure_size=(8.5, 6))
)
```

# Dispersion of Profits

```{python}
#| label: fig-municipalities-profit
#| fig-cap: Dispersion of Profits by State

(
    ggplot(data=df, mapping=aes(x='state', y='profit', fill='state')) 
    + geom_boxplot()
    + coord_flip()
    + scale_y_continuous(limits=(-2, 3.9))
    + labs(x='State',
           y='Profit')
    + theme(legend_position='none',
           figure_size=(8.5, 6))
)
```

# Geographical Distribution

::: {#fig-datawrapper}
```{=html}
<iframe width="840" height="700" src="https://datawrapper.dwcdn.net/gXnz2/2/" title="Datawrapper chart" data-external="1"></iframe>
```
Gasoline Sale Prices by State in Mexico
:::

# Conclusions

In most states, filling a 40-liter car tank costs around $1,000 pesos.

While precise price predictions are difficult, it's reasonable to expect continued volatility in gasoline prices in Mexico during 2025.

The interplay of global oil markets, government policies, and domestic economic conditions will create a dynamic environment.
Consumers should be prepared for potential price fluctuations and consider strategies for managing their fuel expenses.

The energy sector, meanwhile, will be closely watched as Mexico navigates the complex challenges of ensuring affordable and accessible fuel for its population. 

The future of gasoline prices in Mexico remains uncertain, but one thing is clear: it will continue to be a topic of significant importance for both consumers and policymakers.

# Contact

**Jesus L. Monroy**
<br>
*Economist & Data Scientist*

[Medium](https://medium.com/@jesuslm) | [Linkedin](https://www.linkedin.com/in/j3sus-lm) | [Twitter](https://x.com/j3suslm)
