---
title: Gasoline Prices in Mexico Dashboard
author: Jesus L. Monroy
format:
  dashboard:
    theme: flatly
    logo: images/gas.png
    nav-buttons:
      - Portfolio
      - icon: suitcase-lg
        href: https://j3sus.quarto.pub/my-portfolio
      - Linkedin
      - icon: linkedin
        href: https://www.linkedin.com/in/j3sus-lmonroy
      - Twitter
      - icon: twitter
        href: https://x.com/j3suslm
      - Medium
      - icon: medium
        href: https://medium.com/@jesus_lmonroy
jupyter: python3
---

```{python}
import numpy as np
import pandas as pd
import polars as pl
import duckdb as db
import plotly.express as px
from plotnine import *
```

```{python}
conn = db.connect('data/my_database.db')
```

```{python}
df = conn.sql('select * from gas_stations').pl()
```

```{python}
conn.close()
```

```{python}
df = (
    df.select('entidad'
              , 'municipio'
              , 'precio_tar'
              , 'precio_vendedores'
              , 'ganancia')
        .rename({
            'entidad':'state',
            'municipio':'municipality',
            'precio_tar':'gasoline_cost',
            'precio_vendedores':'sale_price',
            'ganancia':'profit',
        })
).with_columns(
    (pl.col('profit')/pl.col('gasoline_cost')).alias('profit%'),
    mun_state=pl.col('municipality')+', '+pl.col('state')
)
```

# Dataset

::: {.card title="Overview"}
## Overview {height=55%}

### Current Situation

- **Rising Prices**

Despite government efforts to stabilize fuel costs, gasoline prices in Mexico have been on the rise.
Some estimates suggest prices could reach MX$30 per liter during 2025.

- **Regional Variations**

Gasoline prices vary significantly across different states in Mexico.
Quintana Roo has the highest average price for regular gasoline, while Veracruz has the lowest.

- **Government Intervention**

The government has implemented measures like a price cap of MX$24 per liter for regular gasoline and has been working to stabilize fuel prices.
However, these efforts have faced challenges.

### Factors Affecting Prices

- **Global Oil Prices**

International oil prices play a significant role in determining gasoline prices in Mexico.

- **Government Policies**

Taxes, subsidies, and regulations implemented by the Mexican government influence fuel prices.

- **Economic Conditions**

Inflation, exchange rates, and other economic factors can impact gasoline prices.

### Challenges and Concerns

- **Impact on Low-Income Families**

Rising gasoline prices put a strain on low-income households, affecting their daily expenses and overall economic well-being.

- **Economic Impact**

Increased fuel costs can have a ripple effect across various sectors of the economy, potentially leading to inflation and affecting businesses.

- **Government Promises**

The government's promises to keep gasoline prices low have been met with skepticism, as prices continue to climb.
:::

## row {height=45%}

```{python}
( 
    df.select(pl.exclude('mun_state'))
        .to_pandas()
        .head(10)
        .style
        .hide()    
        .format({'gasoline_cost': '${:,.2f}',
                 'sale_price': '${:.2f}',
                 'profit': '${:.2f}',
                 'profit%': '{:.2%}',})
)
```

```{python}
states = (
        df.group_by('state')
            .agg(pl.col('gasoline_cost','sale_price','profit', 'profit%').mean())
            .sort('state')
        )
```

```{python}
municipalities = (
        df.group_by('mun_state')
            .agg(pl.col('gasoline_cost','sale_price','profit','profit%').mean())
            .sort('mun_state')
        )
```

# Tables

## row {height=50%}

```{python}
#| tbl-cap: Top 05 States with highest prices
(
    states
        .top_k(5, by='sale_price')
        .to_pandas()
        .style
        .hide()    
        .format({'gasoline_cost': '${:,.2f}',
                 'sale_price': '${:.2f}',
                 'profit': '${:.2f}',
                 'profit%': '{:.2%}',})
)
```

```{python}
#| tbl-cap: Top 05 States with lowest prices
(
    states
        .bottom_k(5, by='sale_price')
        .to_pandas()
        .style
        .hide()    
        .format({'gasoline_cost': '${:,.2f}',
                 'sale_price': '${:.2f}',
                 'profit': '${:.2f}',
                 'profit%': '{:.2%}',})
)
```

## row {height=50%}

```{python}
#| tbl-cap: Top 05 Municipalities with highest prices
(
    municipalities
        .top_k(5, by='sale_price')
        .to_pandas()
        .style
        .hide()    
        .format({'gasoline_cost': '${:,.2f}',
                 'sale_price': '${:.2f}',
                 'profit': '${:.2f}',
                 'profit%': '{:.2%}',})
)
```

```{python}
#| tbl-cap: Top 05 Municipalities with lowest prices
(
    municipalities
        .bottom_k(5, by='sale_price')
        .to_pandas()
        .style
        .hide()    
        .format({'gasoline_cost': '${:,.2f}',
                 'sale_price': '${:.2f}',
                 'profit': '${:.2f}',
                 'profit%': '{:.2%}',})
)
```

# Charts

## row {height=50%}

```{python}
#| label: fig-states
#| fig-cap: Average Gasoline Prices by State

(
    ggplot(states, mapping=aes(x='state', y='sale_price'))
        + geom_bar(stat='identity', fill="#4c72b0")
        + coord_flip()
        + scale_y_continuous(limits=(0, 25))
        + labs(x='',
               y='Gasoline price',
              title='Average Gasoline Prices by State')
        + theme(axis_text_y=element_text(rotation=0),
               figure_size=(8.5, 6))
)
```

```{python}
#| label: fig-states-profit
#| fig-cap: Profit by State

(
    ggplot(states, mapping=aes(x='state', y='profit'))
        + geom_bar(stat='identity', fill="#800020")
        + coord_flip()
        + scale_y_continuous(limits=(0, 3.4))
        + labs(x='',
               y='Profit',
               title='Profits by State')
        + theme(axis_text_y=element_text(rotation=0),
               figure_size=(8.5, 6))
)
```

## row {height=50%}

```{python}
#| label: fig-municipalities
#| fig-cap: Dispersion of Gasoline Prices by State

(
    ggplot(data=df, mapping=aes(x='state', y='sale_price', fill='state')) 
    + geom_boxplot()
    + coord_flip()
    + scale_y_continuous(limits=(20, 25.9))
    + labs(x='',
           y='Gasoline price',
           title='Dispersion of Gasoline Prices by State')
    + theme(legend_position='none',
           figure_size=(8.5, 6))
)
```

```{python}
#| label: fig-municipalities-profit
#| fig-cap: Dispersion of Profits by State

(
    ggplot(data=df, mapping=aes(x='state', y='profit', fill='state')) 
    + geom_boxplot()
    + coord_flip()
    + scale_y_continuous(limits=(-2, 3.9))
    + labs(x='',
           y='Profit',
           title='Dispersion of Profits by State')
    + theme(legend_position='none',
           figure_size=(8.5, 6))
)
```
